//+------------------------------------------------------------------+
//|                                             TradeLossCalculator.mq4 |
//|                        Generated by ChatGPT                       |
//|                                                                  |
//+------------------------------------------------------------------+
#property strict

// Declare variables for user input
double lotSize;
double entryPrice;
double stopLossPrice;
double tickValue;
double tickSize;

//+------------------------------------------------------------------+
//|                                                                  |
//+------------------------------------------------------------------+
void OnStart()
  {
   // Prompt user for input: Lot Size, Entry Price, Stop Loss Price
   lotSize = AskInput("Enter Lot Size:");
   entryPrice = AskInput("Enter Entry Price:");
   stopLossPrice = AskInput("Enter Stop Loss Price:");

   // Get the symbol's properties (tick value and tick size)
   tickValue = MarketInfo(Symbol(), MODE_POINT);
   tickSize = MarketInfo(Symbol(), MODE_TICKSIZE);

   // Calculate the potential loss based on the formula
   double loss = CalculateRisk(lotSize, entryPrice, stopLossPrice, tickValue, tickSize);

   // Display the result in the terminal
   Print("Potential loss for Lot Size ", lotSize, ", Entry Price ", entryPrice, ", and SL at ", stopLossPrice, " is: ", loss, " USD");
  }
//+------------------------------------------------------------------+
//| Function to calculate the risk per trade                         |
//+------------------------------------------------------------------+
double CalculateRisk(double lotSize, double entryPrice, double stopLossPrice, double tickValue, double tickSize)
  {
   // Formula to calculate loss
   return lotSize * tickValue * MathAbs(entryPrice - stopLossPrice) / tickSize;
  }
//+------------------------------------------------------------------+
//| Function to prompt the user for input                            |
//+------------------------------------------------------------------+
double AskInput(string prompt)
  {
   string inputStr;
   double inputVal;
   // Display prompt in terminal
   inputStr = PromptUser(prompt);
   // Convert string to number and return the value
   inputVal = StringToDouble(inputStr);
   return inputVal;
  }
//+------------------------------------------------------------------+
//| Function to create a simple prompt for user input                |
//+------------------------------------------------------------------+
string PromptUser(string prompt)
  {
   string result;
   // Send prompt to terminal for user input
   result = MessageBox(prompt, "Input", MB_OK);
   return result;
  }
